name: Python application

on:
  schedule:
    - cron: '0 11 * * *'  # Runs at 11 am UTC every day
  workflow_dispatch: # Allows manual triggering via a button

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py gspread oauth2client python-dotenv

    - name: Run Python script
      env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
          python bot.py N
